### ISSUE TITLE
Cant talk to external db (mariadb)

### ISSUE THREAD

**Issue by Fjox** [YuaFox/lynx-iberian#17]
Error:
Aug 19 15:26:23 fjox.win mariadbd[656]: 2023-08-19 15:26:23 1474 [Warning] Aborted connection 1474 to db: 'lynxiberian' user: 'foxbot' host: '172.19.0.2' (Got an error reading communication packets)

OS: Ubuntu 22.04.2 LTS

**Comment by Fjox** [comment]
also heres the entire log
```[+] Running 1/0
 ✔ Container foxbot-lynx-1  Created                                                                                                                                                                                                                                                0.0s
Attaching to foxbot-lynx-1
foxbot-lynx-1  |  _._     _,-'""`-._
foxbot-lynx-1  | (,-.`._,'(       |\`-/|
foxbot-lynx-1  |     `-.-' \ )-`( , o o)
foxbot-lynx-1  |           `-    \`_`"'-
foxbot-lynx-1  | ██╗    ██╗███████╗██╗      ██████╗ ██████╗ ███╗   ███╗███████╗     ████████╗ ██████╗
foxbot-lynx-1  | ██║    ██║██╔════╝██║     ██╔════╝██╔═══██╗████╗ ████║██╔════╝     ╚══██╔══╝██╔═══██╗
foxbot-lynx-1  | ██║ █╗ ██║█████╗  ██║     ██║     ██║   ██║██╔████╔██║█████╗          ██║   ██║   ██║
foxbot-lynx-1  | ██║███╗██║██╔══╝  ██║     ██║     ██║   ██║██║╚██╔╝██║██╔══╝          ██║   ██║   ██║
foxbot-lynx-1  | ╚███╔███╔╝███████╗███████╗╚██████╗╚██████╔╝██║ ╚═╝ ██║███████╗        ██║   ╚██████╔╝
foxbot-lynx-1  |  ╚══╝╚══╝ ╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝        ╚═╝    ╚═════╝
foxbot-lynx-1  |
foxbot-lynx-1  | ██╗  ██╗   ██╗███╗   ██╗██╗  ██╗     ██╗██████╗ ███████╗██████╗ ██╗ █████╗ ███╗   ██╗
foxbot-lynx-1  | ██║  ╚██╗ ██╔╝████╗  ██║╚██╗██╔╝     ██║██╔══██╗██╔════╝██╔══██╗██║██╔══██╗████╗  ██║
foxbot-lynx-1  | ██║   ╚████╔╝ ██╔██╗ ██║ ╚███╔╝█████╗██║██████╔╝█████╗  ██████╔╝██║███████║██╔██╗ ██║
foxbot-lynx-1  | ██║    ╚██╔╝  ██║╚██╗██║ ██╔██╗╚════╝██║██╔══██╗██╔══╝  ██╔══██╗██║██╔══██║██║╚██╗██║
foxbot-lynx-1  | ███████╗██║   ██║ ╚████║██╔╝ ██╗     ██║██████╔╝███████╗██║  ██║██║██║  ██║██║ ╚████║
foxbot-lynx-1  | ╚══════╝╚═╝   ╚═╝  ╚═══╝╚═╝  ╚═╝     ╚═╝╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝
foxbot-lynx-1  |
foxbot-lynx-1  |
foxbot-lynx-1  |
foxbot-lynx-1  | 2023-08-19T13:38:19.533Z  INFO 7 --- [           main] d.y.lynxiberian.LynxiberianApplication   : Starting LynxiberianApplication using Java 17-ea with PID 7 (/app/lynxiberian.jar started by root in /app)
foxbot-lynx-1  | 2023-08-19T13:38:19.564Z  INFO 7 --- [           main] d.y.lynxiberian.LynxiberianApplication   : No active profile set, falling back to 1 default profile: "default"
foxbot-lynx-1  | 2023-08-19T13:38:26.501Z  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
foxbot-lynx-1  | 2023-08-19T13:38:27.274Z  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 662 ms. Found 5 JPA repository interfaces.
foxbot-lynx-1  | 2023-08-19T13:38:33.119Z  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
foxbot-lynx-1  | 2023-08-19T13:38:33.200Z  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
foxbot-lynx-1  | 2023-08-19T13:38:33.201Z  INFO 7 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.4]
foxbot-lynx-1  | 2023-08-19T13:38:33.711Z  INFO 7 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
foxbot-lynx-1  | 2023-08-19T13:38:33.719Z  INFO 7 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 12852 ms
foxbot-lynx-1  | 2023-08-19T13:38:35.483Z  INFO 7 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
foxbot-lynx-1  | 2023-08-19T13:38:36.012Z  INFO 7 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.1.6.Final
foxbot-lynx-1  | 2023-08-19T13:38:38.420Z  WARN 7 --- [           main] org.hibernate.orm.deprecation            : HHH90000021: Encountered deprecated setting [javax.persistence.sharedCache.mode], use [jakarta.persistence.sharedCache.mode] instead
foxbot-lynx-1  | 2023-08-19T13:38:39.057Z  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
foxbot-lynx-1  | 2023-08-19T13:38:40.670Z  INFO 7 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@63a5d002
foxbot-lynx-1  | 2023-08-19T13:38:40.692Z  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
foxbot-lynx-1  | 2023-08-19T13:38:40.873Z  INFO 7 --- [           main] SQL dialect                              : HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
foxbot-lynx-1  | 2023-08-19T13:38:41.464Z  WARN 7 --- [           main] o.h.cfg.annotations.EntityBinder         : HHH000457: Joined inheritance hierarchy [dev.yua.lynxiberian.models.Media] defined explicit @DiscriminatorColumn.  Legacy Hibernate behavior was to ignore the @DiscriminatorColumn.  However, as part of issue HHH-6911 we now apply the explicit @DiscriminatorColumn.  If you would prefer the legacy behavior, enable the `hibernate.discriminator.ignore_explicit_for_joined` setting (hibernate.discriminator.ignore_explicit_for_joined=true)
foxbot-lynx-1  | 2023-08-19T13:38:46.995Z  INFO 7 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
foxbot-lynx-1  | 2023-08-19T13:38:47.010Z  INFO 7 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
foxbot-lynx-1  | Adding driver: tumblr
foxbot-lynx-1  | Adding driver: mastodon
foxbot-lynx-1  | Adding driver: instagram
foxbot-lynx-1  | Adding driver: telegram
foxbot-lynx-1  | Adding driver: system
foxbot-lynx-1  | Adding driver: twitter
foxbot-lynx-1  | Adding driver: discord
foxbot-lynx-1  | Adding driver: flickr
foxbot-lynx-1  | Adding driver: local
foxbot-lynx-1  | Adding driver: reddit
foxbot-lynx-1  | Adding driver: flickr
foxbot-lynx-1  | Adding driver: reddit
foxbot-lynx-1  | Adding driver: local
foxbot-lynx-1  | Adding driver: random
foxbot-lynx-1  | 2023-08-19T13:38:52.724Z  WARN 7 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
foxbot-lynx-1  | 2023-08-19T13:38:53.227Z  INFO 7 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@13cc0b90, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@58687fb7, org.springframework.security.web.context.SecurityContextHolderFilter@7d2c9361, org.springframework.security.web.header.HeaderWriterFilter@19f02280, org.springframework.security.web.authentication.logout.LogoutFilter@209f3887, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@426131d7, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@fbe70d8, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@7d2c345d, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@3554bdc0, org.springframework.security.web.session.SessionManagementFilter@6f930e0, org.springframework.security.web.access.ExceptionTranslationFilter@7fef0b40, org.springframework.security.web.access.intercept.AuthorizationFilter@685f5d0d]
foxbot-lynx-1  | 2023-08-19T13:38:54.969Z  INFO 7 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
foxbot-lynx-1  | 2023-08-19T13:38:58.178Z  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
foxbot-lynx-1  | 2023-08-19T13:38:58.363Z  INFO 7 --- [           main] d.y.lynxiberian.LynxiberianApplication   : Started LynxiberianApplication in 42.603 seconds (process running for 46.149)
foxbot-lynx-1  | 2023-08-19T13:38:59.731Z  INFO 7 --- [nio-8080-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
foxbot-lynx-1  | 2023-08-19T13:38:59.732Z  INFO 7 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
foxbot-lynx-1  | 2023-08-19T13:38:59.738Z  INFO 7 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
foxbot-lynx-1  | 2023-08-19T13:39:00.751Z ERROR 7 --- [           main] o.hibernate.id.enhanced.TableStructure   : could not read a hi value - you need to populate the table: buckets_seq
foxbot-lynx-1  | 2023-08-19T13:39:01.799Z ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
foxbot-lynx-1  |
foxbot-lynx-1  | org.springframework.orm.jpa.JpaSystemException: could not read a hi value - you need to populate the table: buckets_seq
foxbot-lynx-1  |        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:321) ~[spring-orm-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233) ~[spring-orm-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550) ~[spring-orm-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152) ~[spring-tx-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:163) ~[spring-data-jpa-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218) ~[spring-aop-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at jdk.proxy2/jdk.proxy2.$Proxy125.save(Unknown Source) ~[na:na]
foxbot-lynx-1  |        at dev.yua.lynxiberian.LynxiberianApplication.onLoad(LynxiberianApplication.java:51) ~[classes!/:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
foxbot-lynx-1  |        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
foxbot-lynx-1  |        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:343) ~[spring-context-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:228) ~[spring-context-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:165) ~[spring-context-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109) ~[spring-boot-3.0.1.jar!/:3.0.1]
foxbot-lynx-1  |        at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80) ~[spring-boot-3.0.1.jar!/:3.0.1]
foxbot-lynx-1  |        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
foxbot-lynx-1  |        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[spring-boot-3.0.1.jar!/:3.0.1]
foxbot-lynx-1  |        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[spring-boot-3.0.1.jar!/:3.0.1]
foxbot-lynx-1  |        at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80) ~[spring-boot-3.0.1.jar!/:3.0.1]
foxbot-lynx-1  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-3.0.1.jar!/:3.0.1]
foxbot-lynx-1  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.1.jar!/:3.0.1]
foxbot-lynx-1  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.1.jar!/:3.0.1]
foxbot-lynx-1  |        at dev.yua.lynxiberian.LynxiberianApplication.main(LynxiberianApplication.java:34) ~[classes!/:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
foxbot-lynx-1  |        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
foxbot-lynx-1  |        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[lynxiberian.jar:na]
foxbot-lynx-1  |        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[lynxiberian.jar:na]
foxbot-lynx-1  |        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[lynxiberian.jar:na]
foxbot-lynx-1  |        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466) ~[lynxiberian.jar:na]
foxbot-lynx-1  | Caused by: org.hibernate.id.IdentifierGenerationException: could not read a hi value - you need to populate the table: buckets_seq
foxbot-lynx-1  |        at org.hibernate.id.enhanced.TableStructure$1$1.execute(TableStructure.java:152) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.id.enhanced.TableStructure$1$1.execute(TableStructure.java:136) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:55) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.jdbc.AbstractReturningWork.accept(AbstractReturningWork.java:34) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcIsolationDelegate.delegateWork(JdbcIsolationDelegate.java:57) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.id.enhanced.TableStructure$1.getNextValue(TableStructure.java:135) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.id.enhanced.PooledOptimizer.generate(PooledOptimizer.java:73) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.id.enhanced.SequenceStyleGenerator.generate(SequenceStyleGenerator.java:536) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:114) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:184) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:129) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:53) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:737) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:721) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
foxbot-lynx-1  |        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
foxbot-lynx-1  |        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:307) ~[spring-orm-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at jdk.proxy2/jdk.proxy2.$Proxy115.persist(Unknown Source) ~[na:na]
foxbot-lynx-1  |        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:610) ~[spring-data-jpa-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
foxbot-lynx-1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
foxbot-lynx-1  |        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
foxbot-lynx-1  |        at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:288) ~[spring-data-commons-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[spring-data-commons-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[spring-data-commons-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516) ~[spring-data-commons-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285) ~[spring-data-commons-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628) ~[spring-data-commons-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168) ~[spring-data-commons-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[spring-data-commons-3.0.0.jar!/:3.0.0]
foxbot-lynx-1  |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.0.3.jar!/:6.0.3]
foxbot-lynx-1  |        ... 38 common frames omitted
foxbot-lynx-1  |
foxbot-lynx-1  |
foxbot-lynx-1  | 2023-08-19T13:39:02.260Z  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
foxbot-lynx-1  | 2023-08-19T13:39:02.266Z  INFO 7 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Destroying Spring FrameworkServlet 'dispatcherServlet'
foxbot-lynx-1  | 2023-08-19T13:39:02.392Z  INFO 7 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
foxbot-lynx-1  | 2023-08-19T13:39:02.398Z  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
foxbot-lynx-1  | 2023-08-19T13:39:02.578Z  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
foxbot-lynx-1 exited with code 0

**Comment by YuaFox** [comment]
Hello,

Currently only mysql is guaranteed to work. Try mysql instead of mariadb.

If you still have problems can you give me your docker-compose.yml without the credentials to reproduce it?

**Comment by Fjox** [comment]
```version: '3.9'

services:
    lynx:
        image: yuafox/lynx-iberian:2023.07
        restart: unless-stopped
        ports:
            - "9385:8080"
        volumes:
            - ./config:/app/config
            - ./plugins:/app/plugins
            - ./storage:/app/storage
        environment:
            DB_URL: "mysql://user:password@172.17.0.1:3306/lynxiberian?createDatabaseIfNotExist=true"

            APP_URL: "https://foxbotmgr.fjox.win"
            LYNX_USERNAME: lynx
            LYNX_PASSWORD: lynx

            # AUTOMATIC MEDIA
            # FLICKR_KEY: "token"
            # FLICKR_SECRET: "token"

            # SOCIAL MEDIA INTEGRATION
            # Uncomment to use it

            # TELEGRAM_TOKEN: "token"
            # TELEGRAM_CHAT: "chat"

            # MASTODON_DOMAIN: "botsin.space"
            # MASTODON_TOKEN: "xxxx"

            # TUMBLR_BLOG: "foxeseveryhour"
            # TUMBLR_TAGS: "fox foxes"
            # TUMBLR_CONSUMER_KEY: "token"
            # TUMBLR_CONSUMER_SECRET: "token"
            # TUMBLR_TOKEN_KEY: "token"
            # TUMBLR_TOKEN_SECRET: "token"

            # TWITTER_API_KEY: "token"
            # TWITTER_API_SECRET: "token"
            # TWITTER_CLIENT_ID: "access_token"
            # TWITTER_CLIENT_SECRET: "access_token"

            # INSTAGRAM_TOKEN: "token"
            # INSTAGRAM_USER: "user_id"
            # INSTAGRAM_TAGS: "#animal #animals #fox #foxes"

            # DISCORD_TOKEN: "Token"
            # DISCORD_ACTIVITY: "Test"

            # Extras
            # MAIN_COMMAND_NAME: "boop"
            # MAIN_COMMAND_DESCRIPTION: "omg!"
            # MAIN_COMMAND_BUCKET: "default"

**Comment by YuaFox** [comment]
I tried your docker-compose with mariadb and it fails, when i swapped to mysql it works, mariadb is not supported.

Also I noticed a bug, if a flickr key is not set it crashes.

Workaround:
```
services:
    lynx:
        image: yuafox/lynx-iberian:2023.07
        restart: unless-stopped
        ports:
            - "9385:8080"
        volumes:
            - ./config:/app/config
            - ./plugins:/app/plugins
            - ./storage:/app/storage
        environment:
            DB_URL: "mysql://root:password@172.17.0.1:3306/lynxiberian?createDatabaseIfNotExist=true"

            APP_URL: "https://foxbotmgr.fjox.win"
            LYNX_USERNAME: lynx
            LYNX_PASSWORD: lynx
            FLICKR_KEY: "123"
            FLICKR_SECRET: "123"
```

I'll fix this bug for the next version #18

**Comment by Fjox** [comment]
well i cant use mysql since i alredy have everything on mariadb

**Comment by YuaFox** [comment]
Currently I don't have plans to add other databases until I have other things more polished.

Feel free fork it and create a PR with mariadb support.

**Comment by Fjox** [comment]
id love too but i cant code java...
